### ISSUE TITLE
Support pro sqlite in memory driver

### ISSUE THREAD

**Issue by Lexinek** [portiny/doctrine#3]
Ahoj, přecházím z kdyby/doctrine, kde jsem používal následující konfiguraci:
```
wrapperClass: OdbavTo\Tests\Utils\DoctrineConnectionMock
memory: true
driver: pdo_sqlite
```

Používal jsem to pro rychlejší běh testů, aby běžely v paměti, zrychlilo je to +- o 70%.

Dá se podobné konfigurace docílit i s portiny?

**Comment by Lexinek** [comment]
Ještě pro úplnost, connection mock:

```php
<?php declare (strict_types=1);

namespace OdbavTo\Tests\Utils;

use Kdyby\Doctrine\Connection;

/**
 * @method onConnect(DoctrineConnectionMock $self)
 */
class DoctrineConnectionMock extends Connection
{
	public $onConnect = [];


	public function connect()
	{
		if (parent::connect()) {
			$this->onConnect($this);
		}
	}
}

```

**Comment by TomasPilar** [comment]
Ahoj,

netestoval jsem, ale podle Doctrine by mělo fungovat toto:

```yaml
doctrine:
	connection:
		driver: pdo_sqlite
		memory: TRUE
		platform: @OdbavTo\Tests\Utils\DoctrineConnectionMock
```
